name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install pypa/build
      run: >-
        python -m
        pip install
        build pytest pytest-timeout scikit-image tensorflow tensorflow-addons
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python -m
        build
        --sdist
        --wheel
        --outdir dist/
        .
    - name: Run tests
      run: >-
        CUDA_VISIBLE_DEVICES='-1' pytest -vv --durations=0 ./tests
